### ISSUE TITLE
about Augmented Sketchy database

### ISSUE THREAD

**Issue by fengwz17** [wchen342/SketchyGAN#1]
I'm a newcomer to deeplearning and also trying to do Sketch2image work. Your project has inspired me. 

Extracting the appropriate edge from the existing image as a dataset was very difficult for me until I discovered your dataset. 

But I was just trying to train on the class "flowers" which I did not find in your tfrecord file. Could you please provide such data as "flowers"?

**Comment by wchen342** [comment]
There is no "flower" class used in our experiments, that is why it is not in the dataset.
I will upload a Flickr crawler as well as data-processing scripts later so that you can crawl whatever images you want from Flickr and create paired image-sketch data yourself.

**Comment by fengwz17** [comment]
Thanks for your reply ! The edge data extracted from images by traditional methods is always too cluttered, and the sketch data is too small. It is difficult to get enough proper edge and sketch data for training. While some other well-performed methods seem too complicated to achieve.

Looking forward to your update !
