### ISSUE TITLE
Running Time too Long

### ISSUE THREAD

**Issue by sitongsu** [wchen342/SketchyGAN#11]
I'm running this model on a computer with TITAN X (Pascal), and my training settings is the same as original. But it takes ~30 seconds/100 iters. Is this running time normal? Here's my output:

    Now at iteration 0. Elapsed time: infs. Average time: infs/iter
    Now at iteration 100. Elapsed time: 173.14804s. Average time: 1.73148s/iter
    Now at iteration 200. Elapsed time: 32.95055s. Average time: 0.32951s/iter
    Now at iteration 300. Elapsed time: 33.15841s. Average time: 0.33158s/iter
    Now at iteration 400. Elapsed time: 32.86847s. Average time: 0.32868s/iter
    Now at iteration 500. Elapsed time: 33.54591s. Average time: 0.33546s/iter
    Now at iteration 600. Elapsed time: 33.57379s. Average time: 0.33574s/iter
    Now at iteration 700. Elapsed time: 33.70091s. Average time: 0.33701s/iter
    Now at iteration 800. Elapsed time: 33.32237s. Average time: 0.33322s/iter
    Now at iteration 900. Elapsed time: 33.29158s. Average time: 0.33292s/iter

Thank you!

**Comment by wchen342** [comment]
Yes, it looks normal. You can try decrease the depth of convolutional layers which can significantly increase training speed but I am not sure how much the quality of generated images will change.

**Comment by sitongsu** [comment]
> Yes, it looks normal. You can try decrease the depth of convolutional layers which can significantly increase training speed but I am not sure how much the quality of generated images will change.

thanks for your reply.I will try the decrease in the later experiments
