### ISSUE TITLE
flickr filter

### ISSUE THREAD

**Issue by YellowPig-zp** [wchen342/SketchyGAN#13]
I am using the provided flickr_crawler.py to retrieve images. For each category ~100,000 images are retrieved. But flickr_filter.py sometimes filters out all the images in a category. Is there any workaround to this? Thanks!

**Comment by wchen342** [comment]
What do you mean by 'filters out all the images in a category'? A little more details will help me understand what was going on. Did you use the function for ImageNet categories to filter MSCOCO categories, or vice versa? That is one of reasons I can think of.

**Comment by YellowPig-zp** [comment]
Hi Dr.Chen. Thanks for the reply. I am using inception_v2, as suggested by the code, to filter the 31 classes in imagenet_share_classes.txt. The program removes all the images in some classes but works fine for other classes.

**Comment by wchen342** [comment]
This is strange. You can try printing out predictions and probabilities the model outputs for images in those faulty classes. If the predictions are correct then the problem is in the python code, otherwise there is something wrong with the model.
