### ISSUE TITLE
original flickr images

### ISSUE THREAD

**Issue by sitongsu** [wchen342/SketchyGAN#14]
hi,Dr.chen,
there is something wrong with the crawling process. So i'm wondering whether you could share the Flickr images(original) with me? I'd appreciate your help.

**Comment by wchen342** [comment]
I can try to find them but I think I have removed most of them since they are too large (I remember it was 2~3TB) and I cannot let them sit on my disks. What is wrong with the Flickr API? Is it still the same problem as in https://github.com/wchen342/SketchyGAN/issues/12?

**Comment by sitongsu** [comment]
thanks for your reply.
i've solved the crawler problem.

**Comment by lucy3589** [comment]
how do you solved this problem?can you tell me ?thank you
