### ISSUE TITLE
The  tfrecord's link is died

### ISSUE THREAD

**Issue by codaibk** [wchen342/SketchyGAN#16]
Hi, Could you please check the tfrecord's link? it seems it is died and returned "404 error"
Thanks

**Comment by yaopengzero** [comment]
could you tell me how to get the tfrecoeds?  
what the features means? :
 features = tf.parse_single_example(
        serialized_example,
        features={
            'ImageNetID': tf.FixedLenFeature([], tf.string),
            'SketchID': tf.FixedLenFeature([], tf.int64),
            'Category': tf.FixedLenFeature([], tf.string),
            'CategoryID': tf.FixedLenFeature([], tf.int64),
            'Difficulty': tf.FixedLenFeature([], tf.int64),
            'Stroke_Count': tf.FixedLenFeature([], tf.int64),
            'WrongPose': tf.FixedLenFeature([], tf.int64),
            'Context': tf.FixedLenFeature([], tf.int64),
            'Ambiguous': tf.FixedLenFeature([], tf.int64),
            'Error': tf.FixedLenFeature([], tf.int64),
            'class_id': tf.FixedLenFeature([], tf.int64),
            'is_test': tf.FixedLenFeature([], tf.int64),
            'image_jpeg': tf.FixedLenFeature([], tf.string),
            'image_small_jpeg': tf.FixedLenFeature([], tf.string),
            'sketch_png': tf.FixedLenFeature([], tf.string),
            'sketch_small_png': tf.FixedLenFeature([], tf.string),
            'dist_map_png': tf.FixedLenFeature([], tf.string),
            'dist_map_small_png': tf.FixedLenFeature([], tf.string),
        }
    )
i only find the tf.parse_single_example ,not find tf.python_io.TFRecordWriter()

**Comment by wchen342** [comment]
@codaibk Please use the script in `data_processing` to crawl your own images.
@yaopengzero The tfrecords are just database files, so each "feature" is just a field of data.
