### ISSUE TITLE
Subset of the augmented sketchy database

### ISSUE THREAD

**Issue by YellowPig-zp** [wchen342/SketchyGAN#17]
Hi Dr. Chen. I understand that your OneDrive business account has expired and it's hard to find a place to hold such a large dataset. However, do you think it is possible to share a subset of the data? Thank you very much in advance!

**Comment by wchen342** [comment]
If you can set up a temporary ftp server or something then I can upload to that.
I remember each file is around 200M, and each class has 5~20 files. Do you want specific classes or less files each class?

**Comment by YellowPig-zp** [comment]
Thank you very much for the reply! Do you mind if I send you the info about connecting to my SFTP server(not FTP)?

**Comment by wchen342** [comment]
Sure. Where will you send me those info?

**Comment by YellowPig-zp** [comment]
Does your school email still work? Otherwise, do you mind sharing your available email? Thanks!

**Comment by wchen342** [comment]
Yes it can still recieve emails.

**Comment by YellowPig-zp** [comment]
Hi Dr. Chen. I have sent you an email with the info for uploading to the SFTP server. Could you please upload the dataset at your convenience? Thank you so much in advance!

**Comment by wchen342** [comment]
Uploaded.

**Comment by vikyzeng** [comment]
Hi Dr. Chen! I also have strong desire for the augmented datasets!  I always failed to crawler images from flickr for connection error. I have sent my info for sftp server to your school email! It is very nice of you to upload the dataset at your convenience! Thank you very much for your kind cooperation!

**Comment by nitish11** [comment]
@vikyzeng @YellowPig-zp Did you get some augmented sketchy database? Could you please share the dataset at my email nitish.bhardwaj11@gmail.com
