### ISSUE TITLE
error ocicured while implementing

### ISSUE THREAD

**Issue by rupambhattacharjee** [wchen342/SketchyGAN#18]
i am getting a error of " string_input_producer requires a non-null input tensor" can you help me please

**Comment by wchen342** [comment]
As the error says, somehow your input to the producer is None.

**Comment by rupambhattacharjee** [comment]
Hi sir, can you tell your email contact where i can contact you regarding this ......it will be better for me please...............you can ping me on bhattacharjeerupam1@gmail.com

**Comment by rupambhattacharjee** [comment]
> As the error says, somehow your input to the producer is None.

<img width="930" alt="error1_15-01-18" src="https://user-images.githubusercontent.com/46022866/51162202-5e351980-18bb-11e9-8fb0-8665f4dd33d8.PNG">

**Comment by wchen342** [comment]
Probably filenames are empty. Maybe files are not in their correct path.

**Comment by rupambhattacharjee** [comment]
sketchy_dir = '/home/ubuntu/VisualSearchAndRecommendation/sketch_to_image/SketchyGAN/data/VSR_Dataset/Sketches'
flickr_dir = '/home/ubuntu/VisualSearchAndRecommendation/sketch_to_image/SketchyGAN/data/VSR_Dataset/Images'


These are the 2 paths i changed .....

**Comment by rupambhattacharjee** [comment]
> Probably filenames are empty. Maybe files are not in their correct path.

i have send you a email(gatech.edu) regarding my doubt........can you please look into it and revert if possible

**Comment by wchen342** [comment]
Ok please stop sending me messages through multiple channels or I will stop replying. I will reply you by email.
