### ISSUE TITLE
Can you upload a trained model

### ISSUE THREAD

**Issue by xuhuaren** [wchen342/SketchyGAN#19]
Hi Dr. Chen. I understand that your OneDrive business account has expired and it's hard to find a place to hold such a large dataset. Can you upload a model weight which could test on the Sketchy dataset. Very appreciate it if you can help me. I want tansfer your model to my own dataset :)

**Comment by wchen342** [comment]
I do not have a model for the newest code but I have an old one which is a little out-dated. If you want I can upload that one.

**Comment by xuhuaren** [comment]
@wchen342 Appreciate it! if it's convenient for you please upload a model. Or can you send me to my custom email address: renxuhua1993@gmail.com

**Comment by wchen342** [comment]
I sent a download link to you.

**Comment by nitish11** [comment]
@wchen342  @xuhuaren Could you please share the trained model to my email address nitish.bhardwaj11@gmail.com.

**Comment by gncgnc** [comment]
Hello Dr. Chen, if you still have the trained model available, would you be willing to share it for a university project? We will embed a retrained version of your model in a user friendly application. We would appreciate your help. You can email me at ( glevi15 [at] ku.edu.tr )
