### ISSUE TITLE
TFrecord preparation for dataset

### ISSUE THREAD

**Issue by Huihui94** [wchen342/SketchyGAN#28]
Dear Dr. Chen,

Thanks for the sharing for code.
I am wondering that is it possible for you to share the code for TFrecord preparation as well? It would be extremely helpful.

Many thanks!

**Comment by rosdyana** [comment]
Hi @Huihui94 , do you mean to generate tfrecord file? you can take a look in my repo ( https://github.com/rosdyana/SketchyGAN/blob/master/src_single/sketchy_to_tfrecord.py )

**Comment by Huihui94** [comment]
Hi @rosdyana, yes, that is exactly what I need to generate the tfrecord!  Thank you so much for your kind help.
