### ISSUE TITLE
Data processing for train the model

### ISSUE THREAD

**Issue by codaibk** [wchen342/SketchyGAN#29]
Dear wchen342,
Currently i want to add one more class in dataset. I tried to run the script in` "data_processing`" folder to created data again but cant.
Could you update the instruction for creating and processing the  dataset in this project ?
Thanks

**Comment by wchen342** [comment]
Do you mean creating tfrecord files? I uploaded the scripts for that.

**Comment by codaibk** [comment]
Hi, thanks for your reply.
Example do i need to use all of these features or not ? because my new class's data doesn't have all of features like following your code such as : WrongPose, Ambiguous...

**Comment by wchen342** [comment]
You can ignore those except for `is_test`.

**Comment by 15702435639** [comment]
Dear wchen342,
        I want to run  * sketchy_to_tfrecord.py , *

**Comment by 15702435639** [comment]
Dear wchen34
         I want to run sketchy_to_tfrecord.py,but I don't know how to make some files,such as testset.txt ,invalid-ambiguous.txt ... ,and if I ignore those ,the code may need big changes.Could you upload files that have been used before?Thank you in advance.

**Comment by codaibk** [comment]
> Dear wchen34
> I want to run sketchy_to_tfrecord.py,but I don't know how to make some files,such as testset.txt ,invalid-ambiguous.txt ... ,and if I ignore those ,the code may need big changes.Could you upload files that have been used before?Thank you in advance.

I think you can ignore those if your dataset doesn't include those features. I did it with my dataset
