### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by mxkai** [wchen342/SketchyGAN#32]
Which version of tensorflow ？I use version of  1.12,but use GPU found a err of"OpKernel was found, but attributes didn't match)
        .  Registered:  device='CPU'"  or  How to use GPU

**Comment by wchen342** [comment]
It is probably a data type error. See:
https://github.com/tensorflow/tensorflow/issues/21464
https://github.com/tensorflow/tensorflow/issues/20369

**Comment by mxkai** [comment]
Thank you very much for your reply.




------------------ 原始邮件 ------------------
发件人: "wchen342"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 下午5:28
收件人: "wchen342/SketchyGAN"<SketchyGAN@noreply.github.com>; 
抄送: "白色蜻蜓"<1502930420@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [wchen342/SketchyGAN] tensorflow version (#32)




It is probably a data type error. See:
 tensorflow/tensorflow#21464
 tensorflow/tensorflow#20369
