### ISSUE TITLE
Could you please share the pre-train model?

### ISSUE THREAD

**Issue by yuqing-liu-dut** [wchen342/SketchyGAN#4]
Hello, I'm trying to train the model. However it is hard to download the entire dataset and perform training because of the hardware constrain. Meanwhile, when downloading the dataset, there are errors in the zip file.
![tim 20180522223756](https://user-images.githubusercontent.com/17153941/40369566-cbc38d30-5e10-11e8-983d-765262c38e55.jpg)
We select all files and download them, unfortunately there are errors from the OneDrive. 
Could you please share the pre-train model? It will be so thankful.

**Comment by wchen342** [comment]
Can you please try downloading them again? I just verified those files and I can download them here with no problems. Maybe you hit the rate limit of OneDrive?
About the pre-trained model, I do have old ones but unfortunately they won't work with current version of code. I can still share them if you want, but you need to do some hack to make them work.

**Comment by yuqing-liu-dut** [comment]
@wchen342  If possible, I want to try the old model. And I will change my tensorflow and other libraries' version to fit it.
Meanwhile, I will try to re-download the files from OneDrive.
Thank you very much for your kindness and help.

**Comment by wchen342** [comment]
I have uploaded an old model [here](https://www.dropbox.com/s/gx9lrwsi8p9wuk5/old_model.tar.gz?dl=0). I also included the code to construct the correct model.

**Comment by yuqing-liu-dut** [comment]
@wchen342  Thank you very much for your kind help. 
However, there are problems applying this model. After downloading this model, the name of 2 folders are with not "skgan" but "wgan". I try to rename them to fit the code, there goes an error, however.  The error goes as below.
![qq 20180607225959](https://user-images.githubusercontent.com/17153941/41133568-40462aa0-6afa-11e8-9017-5258ae3f52da.png)

When checking the files, I've found that there is no json file in neither ckpt folder nor log folder. So I try to copy the .pys from log folder to src_single. But there is no file with same name. Meanwhile, all the files in log folder are some definitions about layers but not entry. 

So could you please tell me how to apply this pre-train model? Thank you very much!

**Comment by wchen342** [comment]
I forgot to include the json file: [link](https://gist.github.com/wchen342/0b3c2d4652c8795c18422477af371ea8).
The graph_ and model_ files are included so you can modify the corresponding files in src_single to build the model that fits the checkpoint. The other files, like train_, are just a framework for convinience. 
You can also try to load the graph definition into default graph directly by `tf.import_graph_def`. inception_score.py has a good example of that.
