### ISSUE TITLE
How could I generate the .tfrecord myself?

### ISSUE THREAD

**Issue by juefeiyuan** [wchen342/SketchyGAN#8]
Hi, Dr. Chen,
I myself have some pairs of sketches and images files, how could I generate the .tfrecord file myself and use your code to run? Thank you

**Comment by wchen342** [comment]
The tfrecord files are just a kind of leveldb, and you can find pretty a lot of tutorials on how to build them. The necessary fields are all in `data_processing/extract_images.py`.
I will try to find the script I used when I get back to my computer later this week, if you need it.

**Comment by juefeiyuan** [comment]
Yes, I need it, I am new to this field, I'll wait for your response, thank you so much.

**Comment by juefeiyuan** [comment]
Hi, Dr. Chen,
Did you find the script to build the .tfrecord files? Thank you for your kindly help.

**Comment by wchen342** [comment]
Hi, i created a gist [here](https://gist.github.com/wchen342/7e6055c2e9fd074329cbabd5fb5e3822). It is the one I used to convert Sketchy Database into tfrecords.
The csv file used in the script is just used to select which classes I want. You can use any other methods to do the same.

**Comment by juefeiyuan** [comment]
Hi, Dr. Chen,
Thank you so much for your help
